### ISSUE TITLE
Source vs src folder

### ISSUE THREAD

**Issue by michalkvasnicka** [zhaokg/Rbeast#14]
There is a small inconsistency at [rbeast_uninstall.m](https://github.com/zhaokg/Rbeast/blob/master/Matlab/rbeast_uninstall.m) and [rbeast_mex_compile.m](https://github.com/zhaokg/Rbeast/blob/master/Matlab/rbeast_mex_compile.m) which used as source directory "src" and your Rbeast distribution package, which used "Source" directory.

**Comment by zhaokg** [comment]
Great suggestion. Thanks. And in the latest version, I made the suggested change.
