### ISSUE TITLE
besat_123_example.txt runing wrong

### ISSUE THREAD

**Issue by HowinMa** [zhaokg/Rbeast#18]
Hi, Mr,zhao. When I run the code 
'Update beast123_raster_example.txt' in R , the line 11 which is 'ndvi3d  = stack(filelist)', it's always report a error'Error in data.frame(values = unlist(unname(x)), ind, stringsAsFactors = FALSE) : Parameter values mean different number of rows: 437, 0''
Would you like to Work out this error? I do not know if it my operation error or something else. 
Waiting for your reply.

**Comment by zhaokg** [comment]
Appreciate the feedback and sorry for the error.  For that example,  the raster package is needed to load a list of Tiff image files.  'stack' is also a function from raster.  Please run "library(raster)" before running the example.  Please also see the updated script file. 

Thanks again for letting me know the issue.

**Comment by HowinMa** [comment]
Thanks for your reply,The following error has alredy fixed.  But there is a another error occoured in line 45 " o=beast123(Y, metadata=metadata,extra=extra) # Default values used for missing parameters " ,which error report:"Error in beast123(Y) : object 'BEASTV4_rexFunction' not found".....
Sorry to borther you again. Your theories and methods are of great significance to the development of our research.
Looking for your reply

**Comment by dirt** [comment]
Which OS do you use?  Windows, Linux or Mac?

Kai

**Comment by HowinMa** [comment]
Windows

**Comment by dirt** [comment]
I can’t reproduce the error on my end. I will recompile a new version for you to install. Give me a few minutes.

Kai

**Comment by HowinMa** [comment]
Tanks for a lot. Professor Zhao

**Comment by dirt** [comment]
Here is a new version; it has been uploaded the github. Use the script below to first uninstall the old version, if any, and install the new version from the posted zip file.

unloadNamespace('Rbeast')       # just in case that Rbeast was loaded
detach(package:Rbeast,unload=T) # it is Ok if reporing error
remove.packages("Rbeast")       # it is Ok if reporing error
install.packages(https://github.com/zhaokg/Rbeast/raw/master/R/Rbeast_1.0.0.zip,     repos = NULL)

Please let me know how it works.

Kai

From: Zhao, Kaiguang
Sent: Monday, August 28, 2023 11:50 PM
To: zhaokg/Rbeast ***@***.***>; zhaokg/Rbeast ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [zhaokg/Rbeast] besat_123_example.txt runing wrong (Issue #18)

Which OS do you use?  Windows, Linux or Mac?

Kai

**Comment by HowinMa** [comment]
Dear Professor Zhao. After your updated, code runing successful！！！
Thanks once more.

![beast123](https://github.com/zhaokg/Rbeast/assets/93090638/6b533f1c-4393-4cb0-a299-514600168555)

**Comment by zhaokg** [comment]
Dear HowinMa , THanks again for reporting the issue. Now I will close this ticket.

Kaiguang
