### ISSUE TITLE
Returning MCMC samples of trend/seasonality functions

### ISSUE THREAD

**Issue by wzhorton** [zhaokg/Rbeast#24]
Hi!

Is it possible to access the posterior samples of the trend and/or seasonality functions directly? Specifically, I'm interested in accessing the sampled vectors that ultimately get averaged together to form the `Y` outputs. If not, could this feature be added?

These would be helpful in order to look at posterior inferences for things like locations of positive slope, which `Rbeast` already provides, but also things like the locations of the local minima/maxima and the presence of particular shapes. Rather than open separate issues for each new inference that might come up, all would be handled if the user is given an option where those posterior samples could be returned directly, probably in the form of a matrix that is size N by n_iterations (assuming vector time-series input).

I recognize that returning posterior samples for ALL parameters is probably not feasible, but hopefully the trend/seasonality vector samples are easy enough structurally to add as an extra return item.

Thank you!

**Comment by zhaokg** [comment]
Hi there,

Thanks a lot your thoughtful and valuable input. (Sorry for not replying earlier.) Originally I had thought about providing an option to dump individual MCMC samples, but I ended not doing so, mostly because the output can be potentially huge. Instead, I just created a version with the gui argument, which gives a sloppy GUI window to show the sampling processes (it was implemented only for Windows not MacOS and Linux).  

Another reason why I didn't implement it is because no other users request for that. If the raw samples are something of interest to you, I can take a stab at it and release it in the next version. 

Again, thanks a lot for the input.

Kaiguang

**Comment by wzhorton** [comment]
Thanks for the reply! This is very interesting to me. I agree that size is cause for concern. My particular use case isn’t very big — I estimate about 5-10mb in memory needed for the trend curve samples — but I only used a few thousand samples for a few hundred datapoints. It’s easy to imagine how more data/samples could lead to heavy memory demands. But I’m not sure if there is a great solution other than a warning message, or maybe only returning the last N samples instead of all iterations.On Mar 8, 2024, at 8:35 PM, zhaokg ***@***.***> wrote:﻿
Hi there,
Thanks a lot your thoughtful and valuable input. (Sorry for not replying earlier.) Originally I had thought about providing an option to dump individual MCMC samples, but I ended not doing so, mostly because the output can be potentially huge. Instead, I just created a version with the gui argument, which gives a sloppy GUI window to show the sampling processes (it was implemented only for Windows not MacOS and Linux).
Another reason why I didn't implement it is because no other users request for that. If the raw samples are something of interest to you, I can take a stab at it and release it in the next version.
Again, thanks a lot for the input.
Kaiguang

**Comment by ebigelow** [comment]
@zhaokg   I would greatly appreciate a flag to return all samples generated during MCMC. This would make BEAST more accessible to a variety of analyses, and it seems like an optional flag would mean memory isn't wasted returning samples if they aren't needed. I'm currently using BEAST for a project and I'd really like to report posterior distributions for abrupt change and trend values for each segment. Ideally, it would also be great if it returned likelihoods for each MCMC sample for assessing model convergence. I'd be happy to contribute in whatever way possible to make this happen soon, though I mostly work in python and am not very experienced with C/C++.

Thank you for your hard work developing and maintaining BEAST.

**Comment by zhaokg** [comment]
> @zhaokg I would greatly appreciate a flag to return all samples generated during MCMC. This would make BEAST more accessible to a variety of analyses, and it seems like an optional flag would mean memory isn't wasted returning samples if they aren't needed. I'm currently using BEAST for a project and I'd really like to report posterior distributions for abrupt change and trend values for each segment. Ideally, it would also be great if it returned likelihoods for each MCMC sample for assessing model convergence. I'd be happy to contribute in whatever way possible to make this happen soon, though I mostly work in python and am not very experienced with C/C++.
> 
> Thank you for your hard work developing and maintaining BEAST.

Dear @ebigelow and @wzhorton ,

Thanks again for your great suggestion. Special thanks to you @ebigelow  for the kind words and the offer to help.   Finally I was able to add a flag to allow dumping the MCMC.  In R and Matlab, the argument is dump.mcmc, and in Python, it is dump_mcmc:

```
beast(Nile, season="none', dump.mcmc=TRUE)          # in R
beast(Nile, season="none', dump_mcmc=True)          # in Python
beast(Nile, 'season',  "none",  "dump.mcmc", true)      # in Matlab
```
In the output, there will be a field called mcmc for the samples.

Thanks again for all your feedbacks. Sorry for the long waiting.
Kaiguang

**Comment by zhaokg** [comment]
Dear [ebigelow](https://github.com/ebigelow) and [wzhorton](https://github.com/wzhorton): Thanks a lot for your important feedbacks. I believe things have been clarified and I will close this issue! If that is not the case, please re-open the issue or create a new issue! Thanks again.
