### ISSUE TITLE
Issue on marginal likelihood

### ISSUE THREAD

**Issue by JJ** [zhaokg/Rbeast#27]
The manual says:

```
the average of the model marginal likelihood; the larger marg_lik, the
better the fitting for a given time series.
```

Would that be the *negative* larger? Foir instance, -1000 would be better than -10, right?

**Comment by JJ** [comment]
Maybe "highest" is the word you're looking for? Or just an example. I can propose a pull request, if you want. Thanks a lot for the quick answer.

**Comment by zhaokg** [comment]
JJ, Thanks a lot. If you can propose a pull request and I will incorporate that. Appreciate your input and contribution.

**Comment by JJ** [comment]
I'm afraid I can't find the specific string in this repository. It's probably in the tar file, I can probably make a change and re-package, but is there maybe another repo with the source for that tar ball?

**Comment by dirt** [comment]
Juan,

Thanks for the note.  Now I upload the whole R package source files under https://github.com/zhaokg/Rbeast/tree/master/R.   Pleases make any changes as needed. I appreciate your input as a contributor.

Best,
Kai

________________________________
