### ISSUE TITLE
RBeast issue -Assuming a complexity prior distribution on the number of change-points with `gammaParameter = 2`

### ISSUE THREAD

**Issue by Maglisa** [zhaokg/Rbeast#3]
Hi,

It seems that there is an issue with Rbeast, it is not running today. My code worked perfectly fine the previous day but today I am getting an error . (see the error output below "=====")

Assuming a complexity prior distribution on the number of change-points with gammaParameter = 2.
Computing posterior parameters... Error in numeric(nTime) : invalid 'length' argument
Is this a temporally thing? Can you help?

Thank you,

**Comment by zhaokg** [comment]
Hi Maglisa, Sorry for not get a chance to see your issue report earlier and for my belated reply. Not sure if my reply is still relevant. In any case,   I am not sure if you are using the right package. I mean there are multiple packages called Rbeast. I am not sure if you are doing time-series analysis or revolutionary tree analysis.  But in my Rbeast package, 'gammaParameter' is never a parameter in the model. 

My best guess is that you are using the beast function from the `beast` package (it seems to have a parameter called gammaParameter), which has nothing to do with `Rbeast`.  Sorry about the confusion. I'd like to name my package as `beast`, but apparently that name has been taken when I released it.
