### ISSUE TITLE
Removal of Credible Interval calculation in version 0.1.22

### ISSUE THREAD

**Issue by RiaanZoetmulder** [zhaokg/Rbeast#33]
Hello Zhao, 

Thanks for your algorithm, it is very useful. I've been using it for a problem at my work. I have version 0.1.19 on one computer and 0.1.22 on another computer. On the second computer I am unable to calculate the credible interval, even when I turn on the ci option (ci = True).

I am using the python version. Could you look into this?

Kind regards,

Riaan

**Comment by Har33m-Sha1kh** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by RiaanZoetmulder** [comment]
Hi Zhao, 

No apologies necessary, it's amazing that you are making this tool available to the community and are maintaining it :)

I will give your suggestion a go and report back!

Kind regards,


Riaan

**Comment by zhaokg** [comment]
Thanks for your understanding Riaan. I posted a new version 0.1.23 on PyPi, which keeps supporting the ci arg while also honoring the dump_ci arg.

**Comment by zhaokg** [comment]
Dear Riaan, I believe things have been clarified and I will close this issue! If that is not the case, please re-open the issue or create a new issue! Thanks a lot!
