### ISSUE TITLE
No such data set: "ndvi"

### ISSUE THREAD

**Issue by ManuelPopp** [zhaokg/Rbeast#34]
The [README.md](https://github.com/zhaokg/Rbeast/tree/master/Python#readme) in [https://github.com/zhaokg/Rbeast/tree/master/Python](https://github.com/zhaokg/Rbeast/tree/master/Python) contains examples which cannot be executed in the current version.

The following line
```python
ndvi, year, datestr = rb.load_example('ndvi')
```
returns
```python
Possible example datasets are:
  nile       : annual streamflow of the River Nile from 1871
  googletrend: monthly Google search popularity of the keyword 'beach'
  yellowstone: biweekly NDVI (greenness) of a Yellowstone site'
  ohio       : satelite reflectanes and NDVI of an Ohio site
  co2        : monthly CO2 concentrations
  covid19    : weekly  new cases and deaths from COVID-19
  simdata    : a 774x3 matrix: three time series of length 774
  imagestack : stacked images of NDVI over a small area
```

Rbeast version 0.1.23
Python version 3.12.5

**Comment by zhaokg** [comment]
Dear ManuelPopp, 

Thanks for letting me know the error. It was my bad. The readme.md in the python folder has not been updated for a while. In the latest version, I changed the ndvi dataset name to "imagestack". 

Now I updated the page here. You can also take a look at the same latest readme file at https://pypi.org/project/Rbeast/.

Thanks again for your important feedbacks. Please let me know if there are any more questions.

Best,
Kaiguang

**Comment by zhaokg** [comment]
I believe things have been clarified and I will close this issue! If that is not the case, please re-open the  issue or create a new issue! Thanks a lot!
